### ISSUE TITLE
同https://github.com/xjflyttp/yii2-oauth/issues/9 issue的问题的解决方法与探讨

### ISSUE THREAD

**Issue by chenbuer** [xjflyttp/yii2-oauth#10]
getUserAttributes()是yii2-user中登录成功之后取出返回数据中的属性值，但是qq登录之后，取出用get_user_info()是返回的数据中是没有id的，也就不能正确入库client_id。

那要是想要正确入库client_id，应该怎么填写呢？

**Comment by chenbuer** [comment]
我觉得这个client_id用qq登录应该是入库openid的，改了可以成功。

**Comment by chenbuer** [comment]
怎么加一个判断，要是$client_id = getUserAttributes()['id']报错，就执行$client_id = getUserAttributes()['openid']  ？？？

**Comment by xjflyttp** [comment]
抱歉，没太看明白你的问题
···
client_id 是QQ的APP标示符
open_id 是 用户标示符
···

如果你要client_id 本身就是由你自己填写的，并不需要额外去请求腾讯接口，直接读client对象属性即可
```
$client->clientId
```



从官方文档的返回值和实测值来看，都不存在一个叫id的键
看下面文档即可知晓

getUserAttributes()方法是通过oauth2.0/me接口获取数据
```
http://wiki.connect.qq.com/%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7openid_oauth2-0
```

getUserInfo()是通过user/get_user_info接口获取数据
```
http://wiki.connect.qq.com/get_user_info
```
