### ISSUE TITLE
please update QqAuth

### ISSUE THREAD

**Issue by whatcq** [xjflyttp/yii2-oauth#11]
`yii\authclient\BaseOAuth::processResponse()` removed

**Comment by xjflyttp** [comment]
try dev branch.
```
https://github.com/xjflyttp/yii2-oauth/commit/151832007c779cc9039106dd2d277621bde90930
```

**Comment by whatcq** [comment]
Thanks
当时解决方案：降级了yii2-authclient
"require": {
        "yiisoft/yii2-authclient": "<=2.0.6",
        "xj/yii2-oauth": "~1.0"
    },
