### ISSUE TITLE
openid not necessary in getMpAccessToken()

### ISSUE THREAD

**Issue by mathedu4all** [xjflyttp/yii2-oauth#15]
/**
     * 获取公众号AccessToken
     * @return MpAccessTokenResult
     * @throws WeixinAccessTokenException
     */
    public function getMpAccessToken()
    {
        try {
            $result = $this->api($this->apiBaseUrl . '/cgi-bin/token', 'GET', [
                'grant_type' => 'client_credential',
                'appid' => $this->clientId,
                'secret' => $this->clientSecret,
                'openid' => $this->getOpenid(), // not necessary!!!!!!!!!
            ]);
            return new MpAccessTokenResult($result);
        } catch (Exception $e) {
            throw new WeixinAccessTokenException($e->getMessage(), $e->getCode());
        }
    }

**Comment by xjflyttp** [comment]
thanks.
