### ISSUE TITLE
yii\web\HttpException: Invalid auth state parameter.

### ISSUE THREAD

**Issue by awebc** [xjflyttp/yii2-oauth#16]
yii\web\HttpException: Invalid auth state parameter.
 /www/yii2/vendor/yiisoft/yii2-authclient/src/OAuth2.php:106
在后台日志老是报这个异常，也查不到，看用户也有登录成功了。
LOG如下：
yii\web\HttpException: Invalid auth state parameter. 
in /www/yii2/vendor/yiisoft/yii2-authclient/src/OAuth2.php:106
Stack trace:

#0 /www/yii2/vendor/yiisoft/yii2-authclient/src/AuthAction.php(415): yii\authclient\OAuth2->fetchAccessToken('8FB6139577AAE0C...')

#1 /www/yii2/vendor/yiisoft/yii2-authclient/src/AuthAction.php(226): yii\authclient\AuthAction->authOAuth2(Object(base\user\components\QqAuth), Array)

#2 /www/yii2/vendor/yiisoft/yii2-authclient/src/AuthAction.php(210): yii\authclient\AuthAction->auth(Object(base\user\components\QqAuth))
#3 [internal function]: yii\authclient\AuthAction->run()

#4 /www/yii2/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array)

#5 /www/yii2/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array)

#6 /www/yii2/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('login', Array)

#7 /www/yii2/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/auth/login', Array)

#8 /www/yii2/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))

#9 /www/yii2/sites/nygq/web/index.php(21): yii\base\Application->run()
#10 {main}

**Comment by xjflyttp** [comment]
你需要抓取当出现此错误时，系统getState保存的校验码和qq返回给你的之间的差异，现在的日志不足以判断问题.

**Comment by awebc** [comment]
我找到原因了。看了日志，有用户是用百度极速版打开登录页面的。
我测试用百度极速版访问我的网站，点击QQ登录，现在QQ登录不是打开腾讯的H5页面，而是直接调起QQ的一个授权界面，授权成功后，会打开我网站的回调网址（/user/auth/qqlogin?code=xxx&state=xxx)，这个时候有的手机（小米手机）会提示用什么浏览器打开，比如我的手机会有这些选项（chrome,小米浏览器，百度极速版），如果我不选择用百度极速版打开，而是选择了chrome,这时就会报这个异常。
有没有解决的方法？

**Comment by xjflyttp** [comment]
state存储于session
state的目的是保证请求者和接受者是同一个人. 
换浏览器等于session丢失了 自然无法通过state校验

最后validateAuthState=false可以不校验state
需要思考这样带来的问题是否可以接受
