### ISSUE TITLE
登录报错

### ISSUE THREAD

**Issue by dragonling** [xjflyttp/yii2-oauth#9]
PHP Notice – yii\base\ErrorException

Undefined index: id
1. in /home/wwwroot/yiike.malitu.com/vendor/dektrium/yii2-user/models/query/AccountQuery.php at line 65
56575859606162636465666768    /**
     * Finds an account by client.
     * @param  ClientInterface $client
     * @return AccountQuery
     */
    public function byClient(ClientInterface $client)
    {
        return $this->andWhere([
            'provider'  => $client->getId(),
            'client_id' => $client->getUserAttributes()['id'],
        ]);
    }
}

**Comment by xjflyttp** [comment]
yii2-user？ 
dump出$client->getUserAttributes()返回值
确保返回数组有id key
直接这么取值可不是好习惯
